---
title: "Make Projection Confidence Intervals"
author: "Pete Cuppernull"
date: "4/20/2022"
output: html_document
---

# Load Libraries
```{r setup, include=FALSE}
library(tidyverse)
```

# Import Documents
```{r}
# Model Paths
  ##If stored in directory
    #paths <- list.files('documents/models', full.names = TRUE)
  ##If stored somewhere else
paths <- list.files('/Volumes/T7/uchicago/word embedding paper/robust models - pooled - 300 v2', full.names = TRUE)

#Session-year Table
session_years <- read_csv('documents/projection_docs/session_years.csv')

#Paths for Dimensions
dims <- c(#"documents/projection_docs/affluence_pairs_v3.csv",
          "documents/projection_docs/friend_pairs_v6.csv",
          "documents/projection_docs/power_pairs_v3.csv",
          "documents/projection_docs/us_them_pairs_v3.csv")

#Names of Dimensions
dim_names <- c("friendship", "power", "usthem")

#Country-Year List
country_list <- "documents/projection_docs/states-country_year-v3.csv"

#Dimension Direction test - 1990 - session 101
# direction_test <- "documents/projection_docs/dim-direction-test.csv"
```

Check that we have all txt files
```{r}
s <- c()
for (i in 1:length(paths)){
  s <- c(s, str_split(paths[i], "_")[[1]][4])
  
}

table(s)

```



# Define Helper Functions
```{r}
#####DEFINE FUNCTIONS##########
#Calculate norm of vector#
norm_vec <- function(x) sqrt(sum(x^2))

#Dot product#
dot <- function(x,y) (sum(x*y))

#Cosine Similarity#
cos <- function(x,y) dot(x,y)/norm_vec(x)/norm_vec(y)

#Normalize vector#
nrm <- function(x) x/norm_vec(x)

#Calculate semantic dimension from antonym pair#
dimension<-function(x,y) nrm(nrm(x)-nrm(y))

#Build Dimension
make_dim <- function(embedding,pairs){
  
    word_dims<-data.frame(matrix(NA,nrow(pairs),300))
    
    for (j in 1:nrow(pairs)){
      rp_word1<-pairs[j,1]
      rp_word2<-pairs[j,2]
      tryCatch(word_dims[j,]<-dimension(embedding[rp_word1,],embedding[rp_word2,]),error=function(e){})
      }
    
    dim_ave<-colMeans(word_dims, na.rm = TRUE)
    dim_ave_n<-nrm(dim_ave)
    
    return(dim_ave_n)
}

```


# Define Main Function
```{r}
make_projection <-  function(model_path, ant_paths, dim_names, country_names){
      #Get session and model numbers from path name
      session_number <- str_split(tail(str_split(model_path, '/')[[1]], 1), "_")[[1]][4]
      model_number <- str_split(str_split(tail(str_split(model_path, '/')[[1]], 1), "_")[[1]][5], "\\.")[[1]][1]
      print(c(session_number, model_number))
      
      #get years
      start_year <- session_years[session_years$session == session_number,]$start_year
      end_year <- session_years[session_years$session == session_number,]$end_year
      
      #Load Model
      model <- read.table(model_path, sep=",")
      #Clean Model
      model <- model %>%
            separate(V1, into = as.character(0:300), sep = " ")
      #Word List
      words <- model %>%
            select("0") %>%
            rename(word = "0")

      #Embedding List
      embeddings <- model %>%
            select(-"0") %>%
            mutate_if(is.character,as.numeric)

      model <- cbind(words, embeddings)[-1,]

      #Create Normalized Version
      model_norm <- model %>%
            mutate_if(is.numeric,scale)

      #Create index from word value
      model <- data.frame(model[,-1], row.names = model[,1])
      model_norm <- data.frame(model_norm[,-1], row.names = model_norm[,1])
      model_norm_mat <- as.matrix(model_norm)
      
      #get country list
      countries <-  read_csv(country_names)
      countries <- countries %>%
          filter(year %in% start_year:end_year) %>%
          distinct(concat_name) %>%
          as.list()
      
      countries <- countries$concat_name
      
      make_single_proj <- function(ant_path, dim_name){
      # Load in Antonym Pairs
      ant_pairs <- read.csv(ant_path, header = FALSE)
      
      #Build Dim
      dim <- make_dim(model, ant_pairs)

      proj <- model_norm_mat %*% dim
      
      proj <- proj %>%
        as.data.frame() %>%
        rownames_to_column("country") %>%
        filter(country %in% countries) %>%
        column_to_rownames("country")
      
      colnames(proj) <- c(dim_name)

      proj
      }
      
      #loop to calculate projections for all countries
      map2_dfc(ant_paths, dim_names, make_single_proj) %>%
        rownames_to_column("country") %>%
        mutate(session_number = session_number,
               model_number = model_number)
}
```

# Map Function Through All Models


```{r, warning=FALSE, message=FALSE}
#splitting this up into two steps to avoid timeout on local computer
results1 <- map_dfr(paths[1:500], ~make_projection(.x, dims, dim_names, country_list))
write_csv(results1, 'documents/projections/pooled_proj_V5a.csv')
results2 <- map_dfr(paths[501:length(paths)], ~make_projection(.x, dims, dim_names, country_list))
write_csv(results2, 'documents/projections/pooled_proj_V5b.csv')
```